version: '3.4'

services:
  robotmna:
    image: robotmna
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "${PORT}:${PORT}"
