version: "3.4"

services:
  robotmna:
    image: robotmna
    container_name: robotmna_node
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
