version: '3.4'

services:
  robotmna:
    image: robotmna
    container_name: robotmna_node
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
